const labels = {
  en: {
    title: 'KNX Viewer', subtitle: 'Group address state changes and read requests', history: '24-hour history on file', viewer: 'Viewer', search: 'Search GA, name, DPT, type or value', clearSearch: 'Clear search', pause: 'Pause', resume: 'Resume live', live: 'Live', paused: 'Paused', loading: 'Loading…', offline: 'Connection unavailable', retry: 'Retry', noViewers: 'No KNX Viewer is available.', unknownViewer: 'The requested KNX Viewer is not available. Check that the node is deployed.', empty: 'No entries in the last 24 hours.', emptySearch: 'No entries match this search in the last 24 hours.', emptyHint: 'New entries will appear here as telegrams arrive.', time: 'Time', telegramType: 'Telegram type', source: 'Source', address: 'GA', name: 'Name', dpt: 'DPT', previous: 'Previous', value: 'Value', newest: 'Most recent', older: 'Older', rows: 'entries on this page', updated: 'Updated', storageError: 'History could not be saved to file.', retained: 'The list shows the last 24 hours. Pausing only stops updates on this page.', authError: 'Authentication required or insufficient permissions. Reopen the page from Node-RED.', requestError: 'Unable to load the history.', responseError: 'The server returned an invalid response.', table: 'Group address state changes and read requests, most recent first', firstValue: 'First value', historical: 'History', loadingHistory: 'Loading history…'
  },
  it: {
    title: 'KNX Viewer', subtitle: 'Cambiamenti di stato e richieste di lettura degli indirizzi di gruppo', history: 'Storico su file di 24 ore', viewer: 'Viewer', search: 'Cerca GA, nome, DPT, tipo o valore', clearSearch: 'Cancella ricerca', pause: 'Pausa', resume: 'Riprendi live', live: 'Live', paused: 'In pausa', loading: 'Caricamento…', offline: 'Connessione non disponibile', retry: 'Riprova', noViewers: 'Nessun KNX Viewer disponibile.', unknownViewer: 'Il KNX Viewer richiesto non è disponibile. Verifica che il nodo sia stato distribuito con Deploy.', empty: 'Nessuna voce nelle ultime 24 ore.', emptySearch: 'Nessuna voce corrisponde alla ricerca nelle ultime 24 ore.', emptyHint: 'Le nuove voci appariranno qui alla ricezione dei telegrammi.', time: 'Ora', telegramType: 'Tipo telegramma', source: 'Sorgente', address: 'GA', name: 'Nome', dpt: 'DPT', previous: 'Precedente', value: 'Valore', newest: 'Più recenti', older: 'Più vecchi', rows: 'voci in questa pagina', updated: 'Aggiornato', storageError: 'Impossibile salvare lo storico su file.', retained: 'L’elenco mostra le ultime 24 ore. La pausa sospende solo gli aggiornamenti di questa pagina.', authError: 'Autenticazione richiesta o permessi insufficienti. Riapri la pagina da Node-RED.', requestError: 'Impossibile caricare lo storico.', responseError: 'Il server ha restituito una risposta non valida.', table: 'Cambiamenti e letture degli indirizzi di gruppo, dal più recente', firstValue: 'Primo valore', historical: 'Storico', loadingHistory: 'Caricamento dello storico…'
  },
  de: {
    title: 'KNX Viewer', subtitle: 'Zustandsänderungen und Leseanfragen der Gruppenadressen', history: '24-Stunden-Verlauf in Datei', viewer: 'Viewer', search: 'GA, Name, DPT, Typ oder Wert suchen', clearSearch: 'Suche löschen', pause: 'Pause', resume: 'Live fortsetzen', live: 'Live', paused: 'Pausiert', loading: 'Wird geladen…', offline: 'Verbindung nicht verfügbar', retry: 'Erneut versuchen', noViewers: 'Kein KNX Viewer verfügbar.', unknownViewer: 'Der angeforderte KNX Viewer ist nicht verfügbar. Prüfen Sie, ob der Knoten bereitgestellt wurde.', empty: 'Keine Einträge in den letzten 24 Stunden.', emptySearch: 'Keine passenden Einträge in den letzten 24 Stunden.', emptyHint: 'Neue Einträge erscheinen hier, sobald Telegramme eintreffen.', time: 'Zeit', telegramType: 'Telegrammtyp', source: 'Quelle', address: 'GA', name: 'Name', dpt: 'DPT', previous: 'Vorher', value: 'Wert', newest: 'Neueste', older: 'Ältere', rows: 'Einträge auf dieser Seite', updated: 'Aktualisiert', storageError: 'Der Verlauf konnte nicht in der Datei gespeichert werden.', retained: 'Die Liste zeigt die letzten 24 Stunden. Die Pause stoppt nur die Aktualisierung dieser Seite.', authError: 'Anmeldung erforderlich oder unzureichende Berechtigungen. Öffnen Sie die Seite erneut über Node-RED.', requestError: 'Der Verlauf konnte nicht geladen werden.', responseError: 'Der Server hat eine ungültige Antwort zurückgegeben.', table: 'Zustandsänderungen und Leseanfragen der Gruppenadressen, neueste zuerst', firstValue: 'Erster Wert', historical: 'Verlauf', loadingHistory: 'Verlauf wird geladen…'
  },
  fr: {
    title: 'KNX Viewer', subtitle: 'Changements d’état et demandes de lecture des adresses de groupe', history: 'Historique sur fichier de 24 heures', viewer: 'Viewer', search: 'Rechercher GA, nom, DPT, type ou valeur', clearSearch: 'Effacer la recherche', pause: 'Pause', resume: 'Reprendre le direct', live: 'Direct', paused: 'En pause', loading: 'Chargement…', offline: 'Connexion indisponible', retry: 'Réessayer', noViewers: 'Aucun KNX Viewer disponible.', unknownViewer: 'Le KNX Viewer demandé est indisponible. Vérifiez que le nœud est déployé.', empty: 'Aucune entrée au cours des dernières 24 heures.', emptySearch: 'Aucune entrée ne correspond à cette recherche dans les dernières 24 heures.', emptyHint: 'Les nouvelles entrées apparaîtront ici à la réception des télégrammes.', time: 'Heure', telegramType: 'Type de télégramme', source: 'Source', address: 'GA', name: 'Nom', dpt: 'DPT', previous: 'Précédent', value: 'Valeur', newest: 'Plus récents', older: 'Plus anciens', rows: 'entrées sur cette page', updated: 'Mis à jour', storageError: 'Impossible d’enregistrer l’historique dans le fichier.', retained: 'La liste affiche les dernières 24 heures. La pause suspend uniquement la mise à jour de cette page.', authError: 'Authentification requise ou autorisations insuffisantes. Rouvrez la page depuis Node-RED.', requestError: 'Impossible de charger l’historique.', responseError: 'Le serveur a renvoyé une réponse non valide.', table: 'Changements et lectures des adresses de groupe, du plus récent au plus ancien', firstValue: 'Première valeur', historical: 'Historique', loadingHistory: 'Chargement de l’historique…'
  },
  es: {
    title: 'KNX Viewer', subtitle: 'Cambios de estado y solicitudes de lectura de las direcciones de grupo', history: 'Historial en archivo de 24 horas', viewer: 'Viewer', search: 'Buscar GA, nombre, DPT, tipo o valor', clearSearch: 'Borrar búsqueda', pause: 'Pausa', resume: 'Reanudar en directo', live: 'En directo', paused: 'En pausa', loading: 'Cargando…', offline: 'Conexión no disponible', retry: 'Reintentar', noViewers: 'No hay ningún KNX Viewer disponible.', unknownViewer: 'El KNX Viewer solicitado no está disponible. Comprueba que el nodo esté desplegado.', empty: 'No hay entradas en las últimas 24 horas.', emptySearch: 'Ninguna entrada coincide con la búsqueda en las últimas 24 horas.', emptyHint: 'Las nuevas entradas aparecerán aquí al recibir los telegramas.', time: 'Hora', telegramType: 'Tipo de telegrama', source: 'Origen', address: 'GA', name: 'Nombre', dpt: 'DPT', previous: 'Anterior', value: 'Valor', newest: 'Más recientes', older: 'Más antiguos', rows: 'entradas en esta página', updated: 'Actualizado', storageError: 'No se pudo guardar el historial en el archivo.', retained: 'La lista muestra las últimas 24 horas. La pausa solo detiene las actualizaciones de esta página.', authError: 'Se requiere autenticación o los permisos son insuficientes. Vuelve a abrir la página desde Node-RED.', requestError: 'No se pudo cargar el historial.', responseError: 'El servidor devolvió una respuesta no válida.', table: 'Cambios y lecturas de las direcciones de grupo, del más reciente al más antiguo', firstValue: 'Primer valor', historical: 'Historial', loadingHistory: 'Cargando historial…'
  },
  zh: {
    title: 'KNX Viewer', subtitle: '组地址状态变化和读取请求', history: '文件保存最近 24 小时的历史', viewer: 'Viewer', search: '搜索 GA、名称、DPT、类型或值', clearSearch: '清除搜索', pause: '暂停', resume: '恢复实时', live: '实时', paused: '已暂停', loading: '正在加载…', offline: '连接不可用', retry: '重试', noViewers: '没有可用的 KNX Viewer。', unknownViewer: '请求的 KNX Viewer 不可用。请确认节点已部署。', empty: '最近 24 小时没有记录。', emptySearch: '最近 24 小时没有符合搜索条件的记录。', emptyHint: '收到报文后，新记录将在此显示。', time: '时间', telegramType: '报文类型', source: '来源', address: 'GA', name: '名称', dpt: 'DPT', previous: '先前值', value: '值', newest: '最新', older: '更早', rows: '条记录显示在本页', updated: '更新于', storageError: '无法将历史记录保存到文件。', retained: '列表显示最近 24 小时的记录。暂停仅停止本页更新。', authError: '需要身份验证或权限不足。请从 Node-RED 重新打开此页面。', requestError: '无法加载历史记录。', responseError: '服务器返回了无效响应。', table: '组地址状态变化和读取请求，最新在前', firstValue: '首个值', historical: '历史', loadingHistory: '正在加载历史记录…'
  }
}

export function getLabels (requestedLanguage) {
  const language = String(requestedLanguage || 'en').toLowerCase().split(/[-_]/)[0]
  return { language: labels[language] ? language : 'en', text: labels[language] || labels.en }
}
