title: KNX Ultimate Documentation
description: Documentation for node-red-contrib-knx-ultimate
theme: minima
baseurl: "/node-red-contrib-knx-ultimate"
url: "https://supergiovane.github.io"
markdown: kramdown
feed: false
kramdown:
  input: GFM
exclude:
  - feed.xml
  - index.md
  - node_modules
  - scripts
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
defaults:
  - scope:
      path: "wiki"
    values:
      layout: wiki
