title: KNX Ultimate Documentation
description: Documentation for node-red-contrib-knx-ultimate
theme: minima
baseurl: "/node-red-contrib-knx-ultimate"
url: "https://supergiovane.github.io"
markdown: kramdown
plugins:
  - jekyll-polyglot
feed: false
polyglot:
  default_lang: en
  languages:
    - en
    - it
    - de
    - fr
    - es
    - zh-CN
  translate_links: false
  include: ["_data/wiki-nav.json"]
  exclude_from_localization:
    - assets
    - Gemfile
kramdown:
  input: GFM
exclude:
  - feed.xml
  - index.md
  - node_modules
  - scripts
  - Gemfile
defaults:
  - scope:
      path: "wiki"
    values:
      layout: wiki
